# Generated by Django 4.2 on 2025-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshop', '0002_alter_product_discount_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
